### ISSUE TITLE
Django 1.11.x support?

### ISSUE THREAD

**Issue by mengkheang** [APSL/puput#114]
I already have a site running on django 1.11 when is it gonna be supported?

**Comment by FlipperPA** [comment]
I haven't tested it yet, but you may be able to just change "1.11" to "2" on this line:

https://github.com/APSL/puput/blob/master/setup.py#L44

Give that a whirl?

**Comment by mengkheang** [comment]
let see i'll fork it :)

**Comment by mengkheang** [comment]
@FlipperPA how can i run test again django 1.11.x ?

**Comment by FlipperPA** [comment]
I've been busy on other projects, but I think I'll have some cycles this weekend to give Puput a test under 1.11, and hopefully finish up the Stream Body PRs. :)

**Comment by mengkheang** [comment]
@FlipperPA hopefully soon :)

**Comment by marctc** [comment]
Apparently it works.

**Comment by mengkheang** [comment]
awesome thank @marctc I'll try it when I got home
