### ISSUE TITLE
"Twitter cards" on posts

### ISSUE THREAD

**Issue by sabueso** [APSL/puput#121]
Hi! 

Maybe a good improvement is to develope "Twitter cards" for posts, to share more graphically posts wroten in a blog.

A good example of "Twitter card" for a resource:

![seleccion_340](https://user-images.githubusercontent.com/2073374/27766741-31886b3a-5edb-11e7-9a67-c111b7b4fbb4.png)

Somebody thinking about that? Will a PR wellcomed? :-P

Thanks!

**Comment by sabueso** [comment]
My mistake: I'm using a forked version of Puput from https://github.com/MiltonLn and if StreamBody is defined and not normal "body", the twitter cards are not validated due the lack of "description" field in template rendering.

I'll apply a monkey-patch until some decision is taken from his PR

**Comment by marctc** [comment]
Sorry to hear that you miss time with that. We are so close to have StreamBody in puput!

**Comment by SalahAdDin** [comment]
What's stream body?

**Comment by sabueso** [comment]
@SalahAdDin you can follow this here => https://github.com/APSL/puput/pull/83
