### ISSUE TITLE
Error with django 1.11: Context must be a dict rather than RequestContext

### ISSUE THREAD

**Issue by jojolalpin** [APSL/puput#123]
**Quick fix : Keep with django 1.10**

When rendering base.html line 46 for an entry end point:
Context must be a dict rather than RequestContext.
/usr/local/lib/python3.5/site-packages/django/template/context.py in make_context, line 287

error happens in puput_tags.py in show_comments at template rendering.

**Comment by marctc** [comment]
I wasn't able to reproduce it. Can you provide me more details?
thanks

**Comment by jojolalpin** [comment]
Hi marc,
Sorry I can't right now, too busy.
But django doc tells about a change since 1.11 about context and using 1.10
solved the problem.

Le mer. 26 juil. 2017 09:19, Marc Tudurí <notifications@github.com> a
écrit :

**Comment by Speedy1991** [comment]
there was a breaking change [here](https://docs.djangoproject.com/en/1.11/releases/1.11/#django-template-backends-django-template-render-prohibits-non-dict-context)
