### ISSUE TITLE
Puput Page not found (404)

### ISSUE THREAD

**Issue by jeffgodwyll** [APSL/puput#129]
I've set up puput [on top of a fresh wagtail instal](http://puput.readthedocs.io/en/latest/setup.html#installation-on-top-of-wagtail)l. I noticed support for Django 1.11+ is quite recent.

Anything I'm missing?

```
Page not found (404)
Request Method:	GET
Request URL:	http://127.0.0.1:8000/blog/
Raised by:	wagtail.wagtailcore.views.serve
```

```
$ cat requirements.txt
Django>=1.11,<1.12
wagtail>=1.11,<1.12
puput==0.9
```

**Comment by marctc** [comment]
I'll check it ASAP. thanks

**Comment by jeffgodwyll** [comment]
@marctc any updates?

**Comment by marctc** [comment]
@jeffgodwyll did you create any blog page or executed `python manage.py puput_initial_data` command?

**Comment by jeffgodwyll** [comment]
ha! thanks. I missed that step. I'd love to add that to that section of the docs if it's fine by you?

**Comment by marctc** [comment]
Sure. But keep in mind that if someone has a previously defined page structure in his Wagtail project it not recommended to execute that command. Only should be executed if there are no any other pages.
