### ISSUE TITLE
Puput perhaps needs add something about django-compressor in docs.

### ISSUE THREAD

**Issue by Pyloons** [APSL/puput#131]
### Meet the trouble
When I ready to deploy my blog,I give the `production.py` to gunicorn run,but it always show error 500.
### Hard working
After many tries in puzzle,I found the problem is in the templates.So I set many many `{% comment %}sth{% endcomment %}` in `base.html`.Finally I found the tag `{% compress %}` is the source of trouble.
### Complain a lot
Wagtail's doc said they [remove django-compressor in ver1.4](https://github.com/wagtail/wagtail/blob/4caa8601494a458348060e5f7cc988afcb960937/docs/releases/1.4.rst#removal-of-django-compressor).
Puput add a `'compressor'` in `INSTALL_APPS`,**BUT** never told us add `'compressor.finders.CompressorFinder',` in `STATICFILES_FINDERS` [as the quickstart of django-compressor say](https://django-compressor.readthedocs.io/en/latest/quickstart/).
### My suggest
My site is based on wagtail,but I thought there will are the same problem on django.
It's hard to add this option automatically but I hope documents could told beginners add `'compressor.finders.CompressorFinder',` in `STATICFILES_FINDERS` if you want to deploy the blog.
#132 Remove Compress

**Comment by marctc** [comment]
Hi @Pyloons,

I'm planning to remove django-compressor from the dependencies as Wagtail did in previous versions. It's true that compressor is tricky for deployments and also caused other issues like #91. Are you able to make a PR in order to get rid off the compresser dependency?

**Comment by marctc** [comment]
Fixed in #134
