### ISSUE TITLE
Non English SLUG

### ISSUE THREAD

**Issue by ysharoiko** [APSL/puput#142]
Tryed 
Was trying
Django==1.11.8
wagtail==1.13.1
puput==0.9.1

Created blog with slug name test - Everything was perfect.
Then created blog with NON ENGLISH slug name блог-лабораториума
And got error accessing page:

Request Method: | GET
-- | --
http://localhost:8000/%D0%B1%D0%BB%D0%BE%D0%B3-%D0%BB%D0%B0%D0%B1%D0%BE%D1%80%D0%B0%D1%82%D0%BE%D1%80%D0%B8%D1%83%D0%BC%D0%B0/
1.11.8
NoReverseMatch
Reverse for 'blog_page_feed_slug' with keyword arguments '{'blog_path': '%D0%B1%D0%BB%D0%BE%D0%B3-%D0%BB%D0%B0%D0%B1%D0%BE%D1%80%D0%B0%D1%82%D0%BE%D1%80%D0%B8%D1%83%D0%BC%D0%B0'}' not found. 1 pattern(s) tried: ['(?P<blog_path>[-\\w\\/]+)/feed/$']
/home/user/Env/bl_test/lib/python3.5/site-packages/django/urls/resolvers.py in _reverse_with_prefix, line 497
/home/user/Env/bl_test/bin/python
3.5.2
['/home/user/django_wagtail/lsite',  '/home/user/Env/bl_test/lib/python35.zip',  '/home/user/Env/bl_test/lib/python3.5',  '/home/user/Env/bl_test/lib/python3.5/plat-x86_64-linux-gnu',  '/home/user/Env/bl_test/lib/python3.5/lib-dynload',  '/usr/lib/python3.5',  '/usr/lib/python3.5/plat-x86_64-linux-gnu',  '/home/user/Env/bl_test/lib/python3.5/site-packages']
Чт, 7 Дек 2017 15:15:39 +0000

**Comment by ysharoiko** [comment]
When I renamed slug in english error disappeared.
Is there a way to make translite before saving? Maybe somebody knows where to fix it? I would be glad to here )

**Comment by marctc** [comment]
Hi @ysharoiko,
Try changing this: https://github.com/APSL/puput/issues/122
