### ISSUE TITLE
Not working data links

### ISSUE THREAD

**Issue by ysharoiko** [APSL/puput#143]
I added blog record with slug name test. 
And added subrecord blog-test-1

And it perfectly shows in 
http://localhost:8000/test/

But on that page theres a link 
http://localhost:8000/test/2017/12/07/blog-test-1/

Which absolutly not working

Request Method: | GET
-- | --
http://localhost:8000/test/2017/12/07/blog-test-1/
wagtail.wagtailcore.views.serve

**Comment by marctc** [comment]
Hi @ysharoiko,
Have you checked this?? http://puput.readthedocs.io/en/latest/sites.html

**Comment by MiltonLn** [comment]
Closing this due to the answer provided by Marc, please re-open if this is still an issue.
