### ISSUE TITLE
Following the guide on ReadTheDocs installing puput ontop of Wagtail does not work

### ISSUE THREAD

**Issue by thexiaozhuzhu** [APSL/puput#146]
Following the guide below does not work
[](https://puput.readthedocs.io/en/latest/setup.html#installation-on-top-of-wagtail)

The reason for this being that pip install puput gets you an old version 0.9.1
https://pypi.python.org/pypi/puput/0.9.1

You get a compress error which I managed to fix by reading up
https://github.com/APSL/puput/pull/134
(Although I am not sure if I fixed everything)

Specifically, I edited the first two files listed in the above link which is
base.html & __init__.py
Took me a while but I found the files hidden in
virtualenv/lib/python3.4/site-packages/puput/__init__.py
virtualenv/lib/python3.4/site-packages/puput/templates/puput/base.html

Hope this is helpful for people trying to install Puput on top of Wagtail!

**Comment by chacha68600** [comment]
I had the same problem, and fixed the first two files as you did.
And now I have problem with "Waiting for response from http://127.0.0.1:8000/blog"
and I am not able to see the page.
However, blog_admin page is working well.
Do you have any idea what's going on within my situation?

**Comment by autoferrit** [comment]
I have this issue as well, will this be released / fixed any time soon?

**Comment by marctc** [comment]
Hi @autoferrit. I uploaded a new release (0.9.2). Can you try it now?

**Comment by MiltonLn** [comment]
Closing this due to the release @marctc mentioned, please re-open if the issue still exists.
