### ISSUE TITLE
El Pagination Show_Paginator printing objects in plain text

### ISSUE THREAD

**Issue by kennybrich** [APSL/puput#149]
I had an issue with my Puput project where the show_paginator tag in my blog would show the El Pagination objects as raw text instead of clickable links.

I was able to resolve the issue by removing the El Pagination templates within Puput, removing the puput "paginate" and "show_paginator" tags, and including the El Pagination app separately in my project. 

I don't know what was the cause of this issue, I just wanted to put this out there in case anyone else runs into the same issue.

**Comment by marctc** [comment]
Hi,
Try updating the django-el-pagination. We will release a new patch soon changing the default version in setup.py for django-el-pagination.

**Comment by kennybrich** [comment]
I did try multiple versions of el pagination. Specifically, 3.2.4 and 3.2.3, with the same result.

**Comment by csalom** [comment]
Hi,
Try to use django-el-pagination==3.1.0.
I get the same issue and this version solves it.
As @marctc said we will work in a new patch as soon as possible.

**Comment by kennybrich** [comment]
Alright, I may give that a try. Thanks for all the feedback.

**Comment by csalom** [comment]
I've create this [PR](https://github.com/APSL/puput/pull/150) with the fix for el_pagination>=3.2.1

**Comment by vanducng** [comment]
> Hi,
> Try to use django-el-pagination==3.1.0.
> I get the same issue and this version solves it.
> As @marctc said we will work in a new patch as soon as possible.

This works bro, thank you.
