### ISSUE TITLE
support wagtail 2.0 

### ISSUE THREAD

**Issue by yvess** [APSL/puput#151]
wagtail 2.0 was released! time for puput to follow!

It would be nice if puput would be soon compatible. 
I have seen this pull request #147, but there doesn't seem to be much in it. 
Is somebody working at it?

**Comment by marctc** [comment]
Hi @yvess,
I think that nobody is working on it because the release of wagtail 2.0 is quite recent. I just opened the PR to see if the tests pass but it seems that some work is needed in order that puput will work with wagtail 2.0. Are you able to do it? 

thanks

**Comment by MiltonLn** [comment]
I think I can help with this :)

**Comment by yvess** [comment]
When I need it and nothing already is available I will try to work on it, or help somebody else to speed it up.
It would be great if anybody who works at it would make a link to his branch in this issue.

I just want to prevent that multiple people work on the same thing.

**Comment by marctc** [comment]
@MiltonLn will do it. So don't worry about it.

**Comment by sky-code** [comment]
I hope it does not take long, I really need this update

**Comment by MiltonLn** [comment]
I've made a really good progress on this, now I have Puput working with wagtail 2.0 but I realized that the wagtail team didn't add the  `Code Snippet` or `Blockquote` to Draftail by default. 

I could implement the `Blockquote` and now it's working, but I'm struggling with the `Code Snippet` one. There is a huge lack of documentation on how to implement those draftail features, I've been working with just [this](http://docs.wagtail.io/en/v2.0/advanced_topics/customisation/extending_draftail.html?highlight=draftail).

If any of you have implemented features for draftail and can give me a hand this is the code I have so far, trying to put the code snippets to work:

```python
import wagtail.admin.rich_text.editors.draftail.features as draftail_features
from wagtail.admin.rich_text.converters.html_to_contentstate import InlineStyleElementHandler, BlockElementHandler
from wagtail.core import hooks


@hooks.register('register_rich_text_features')
def register_blockquote_feature(features):
    """
    Registering the `blockquote` feature, which uses the `blockquote` Draft.js block type,
    and is stored as HTML with a `<blockquote>` tag.
    """
    feature_name = 'blockquote'
    type_ = 'blockquote'
    tag = 'blockquote'

    control = {
        'type': type_,
        'label': '❝',
        'description': 'Quote',
        'element': 'blockquote',
    }

    features.register_editor_plugin(
        'draftail',
        feature_name,
        draftail_features.BlockFeature(control)
    )

    features.register_converter_rule(
        'contentstate',
        feature_name,
        {
            'from_database_format': {tag: BlockElementHandler(type_)},
            'to_database_format': {'block_map': {type_: tag}},
        }
    )
    features.default_features.append(feature_name)


@hooks.register('register_rich_text_features')
def register_codeblock_feature(features):
    feature_name = 'code-block'
    type_ = 'code-block'
    tag = 'pre'

    control = {
        'type': type_,
        'label': '</>',
        'description': 'Code Snippet',
        'element': 'pre',
    }

    features.register_editor_plugin(
        'draftail',
        feature_name,
        draftail_features.BlockFeature(control)
    )

    features.register_converter_rule(
        'contentstate',
        feature_name,
        {
            'from_database_format': {tag: BlockElementHandler(type_)},
            'to_database_format': {'block_map': {type_: tag}},
        }
    )

    features.default_features.append(feature_name)
```

I hope to finish this ASAP, next step would be to test all blog features 😄 

P.S: Is worth to say that I'll drop support for Python 2.7 with this upgrade

**Comment by MiltonLn** [comment]
Take a look at #152 😄
