### ISSUE TITLE
Can't override fields in EntryAbstract subclass

### ISSUE THREAD

**Issue by alexgleason** [APSL/puput#16]
Mainly wanting to post this to link to django/django#5122 where the problem seems to be resolved. Django gets upset when you try to override a model field from a subclass. In my case, I want to override `body` from EntryAbstract in a subclass but I can't. There's no reason you shouldn't be able to, since the parent class is abstract. This makes the EntryAbstract class far less useful until the problem is fixed.

**Comment by marctc** [comment]
@alexgleason is this possible right now?

**Comment by MiltonLn** [comment]
Closing this because it's possible on Django since 2016
