### ISSUE TITLE
blog_admin returns a 404 error

### ISSUE THREAD

**Issue by timcknowles** [APSL/puput#176]
I have followed the docs to add puput to an existing wagtail project. 

I seem to be able to view a blog at http://127.0.0.1:8000/blog. I can create new posts by making child pages of /blog. However if I try to edit the blog via http://127.0.0.1:8000/blog_admin/ I get a 404 error

Request Method: | GET
-- | --
http://127.0.0.1:8000/blog_admin/
wagtail.core.views.serve

Any ideas much appreciated?

**Comment by csalom** [comment]
Hi @timcknowles,
can you show us how have you set puput urls, please?

**Comment by MiltonLn** [comment]
@timcknowles Could you solve the issue? please let us know

**Comment by MiltonLn** [comment]
Closing, if this is still causing problems for you @timcknowles please reopen
