### ISSUE TITLE
WARNINGS: ?: (urls.W005) URL namespace ..

### ISSUE THREAD

**Issue by roderik333** [APSL/puput#186]
puput==1.0.3
wagtail==2.3
Fresh install (my first entry into wagtail/puput)
```
$ ./manage.py runserver
?: (urls.W005) URL namespace 'wagtailadmin_api_v1' isn't unique. You may not be able to reverse all URLs in this namespace
?: (urls.W005) URL namespace 'wagtailadmin_api_v1:documents' isn't unique. You may not be able to reverse all URLs in this namespace
?: (urls.W005) URL namespace 'wagtailadmin_api_v1:images' isn't unique. You may not be able to reverse all URLs in this namespace
?: (urls.W005) URL namespace 'wagtailadmin_api_v1:pages' isn't unique. You may not be able to reverse all URLs in this namespace
?: (urls.W005) URL namespace 'wagtailadmin_collections' isn't unique. You may not be able to reverse all URLs in this namespace
?: (urls.W005) URL namespace 'wagtailadmin_pages' isn't unique. You may not be able to reverse all URLs in this namespace
?: (urls.W005) URL namespace 'wagtaildocs' isn't unique. You may not be able to reverse all URLs in this namespace
?: (urls.W005) URL namespace 'wagtailembeds' isn't unique. You may not be able to reverse all URLs in this namespace
?: (urls.W005) URL namespace 'wagtailforms' isn't unique. You may not be able to reverse all URLs in this namespace
?: (urls.W005) URL namespace 'wagtailimages' isn't unique. You may not be able to reverse all URLs in this namespace
?: (urls.W005) URL namespace 'wagtailredirects' isn't unique. You may not be able to reverse all URLs in this namespace
?: (urls.W005) URL namespace 'wagtailsearch_admin' isn't unique. You may not be able to reverse all URLs in this namespace
?: (urls.W005) URL namespace 'wagtailsites' isn't unique. You may not be able to reverse all URLs in this namespace
?: (urls.W005) URL namespace 'wagtailsnippets' isn't unique. You may not be able to reverse all URLs in this namespace
?: (urls.W005) URL namespace 'wagtailusers_groups' isn't unique. You may not be able to reverse all URLs in this namespace
?: (urls.W005) URL namespace 'wagtailusers_users' isn't unique. You may not be able to reverse all URLs in this namespace
```

If this is a bug.. for anyone else but me it can easily be solved by adding namespace to the urls, hence:
```
yoursite/urls.py
url(r'',include(puput_urls, namespace='puput'))
```
```
puput/urls.py: 
app_name = 'puput'
all occurences of "reverse(" must read "reverse('puput: ...'"
```
So far this looks to solve the problem..(mind I've been working with puput/wagtail for all of an hour.)

**Comment by chobijaeyu** [comment]
thanks,I have solved the problem .
but other problem came out.
`ERRORS:
blog.BlogPage.page_ptr: (fields.E304) Reverse accessor for 'BlogPage.page_ptr' clashes with reverse accessor for 'BlogPage.page_ptr'.
        HINT: Add or change a related_name argument to the definition for 'BlogPage.page_ptr' or 'BlogPage.page_ptr'.
blog.BlogPage.page_ptr: (fields.E305) Reverse query name for 'BlogPage.page_ptr' clashes with reverse query name for 'BlogPage.page_ptr'.
        HINT: Add or change a related_name argument to the definition for 'BlogPage.page_ptr' or 'BlogPage.page_ptr'.
puput.BlogPage.page_ptr: (fields.E304) Reverse accessor for 'BlogPage.page_ptr' clashes with reverse accessor for 'BlogPage.page_ptr'.
        HINT: Add or change a related_name argument to the definition for 'BlogPage.page_ptr' or 'BlogPage.page_ptr'.
puput.BlogPage.page_ptr: (fields.E305) Reverse query name for 'BlogPage.page_ptr' clashes with reverse query name for 'BlogPage.page_ptr'.
        HINT: Add or change a related_name argument to the definition for 'BlogPage.page_ptr' or 'BlogPage.page_ptr'.

`

**Comment by lucasmoeskops** [comment]
You get this error because you have both installed Wagtail and Puput in your site's urls.py.

Two options:
* Remove the wagtail urls (and imports), Puput will manage them for you. Note that `/admin` becomes `/blog_admin`.
* Add `PUPUT_AS_PLUGIN = True` to your settings file, now Puput will leave managing wagtail urls to you.

**Comment by MiltonLn** [comment]
Thanks for the answer @lucasmoeskops, I'm closing this now, if you're still having problems with this please reopen @chobijaeyu @roderik333
