### ISSUE TITLE
Support wagtail 2.4

### ISSUE THREAD

**Issue by matburnham** [APSL/puput#188]
Wagtail 2.3 keeps telling me that it has a newer version available.  I tracked the cause down to puput's dependency on wagtail < 2.4. `puput 1.0.3 has requirement wagtail<2.4,>=2.0, but you'll have wagtail 2.4 which is incompatible.`

Is it a trivial fix to support the newer Wagtail or is 2.4 specifically excluded?

**Comment by sam-mi** [comment]
This line produces an offline compression error when using compressor with 2.4 and wagtail react streamfield 1.2.0 in prodution:

https://github.com/APSL/puput/blob/c3294f6bb0dd784f881ce9e3089cbf40d0528e47/puput/templates/wagtailadmin/pages/_editor_css.html#L8

It looks like the file might not even be needed any more? Overriding that template by copying the file from wagtail into the project solved the issue for me.

**Comment by Fandekasp** [comment]
Is Puput still actively maintain? I was considering using it, but the lack of recent commits and roadmap is a bit worrying.

**Comment by MiltonLn** [comment]
Hi, thanks for reporting, I'll take a look in the coming days.

@Fandekasp it is actively maintained, just haven't had the bandwidth to tackle some issues, there's not so much pending work to update it though. PRs are welcome :D

**Comment by auvipy** [comment]
uring template rendering
In template /home/asif/upwork/mezprs/phoblog/puput/templates/puput/base.html, error at line 26

Reverse for 'entry_page_serve_slug' not found. 'entry_page_serve_slug' is not a valid view function or pattern name.

**Comment by auvipy** [comment]
https://github.com/APSL/puput/pull/192 opened to fix existing incompatibilities please review and suggest fixes

**Comment by lucasmoeskops** [comment]
This seems fixed in the master branch but not yet on PyPI.

**Comment by marctc** [comment]
ok, i will releasae a new version then

**Comment by MiltonLn** [comment]
Did you released @marctc ?

**Comment by marctc** [comment]
Sorry for the delay. Done now!
