### ISSUE TITLE
Automatically generated slugs may contain special characters

### ISSUE THREAD

**Issue by sumpfralle** [APSL/puput#189]
I am using puput for a blog. The articles are written in German, thus the titles can contain umlauts.
Surprisingly the generated slugs keep the umlauts instead of converting them to ascii characters.
Thus the reverse URL resolution when browsing the blog fails, since the URL patterns allow only ascii characters.

Is this an issue of puput or should I open this issue with wagtail itself?

Thank you for your time!

**Comment by climu** [comment]
As one can see in the referenced issue, this gave us some trouble too.

**Comment by MiltonLn** [comment]
Fixed!
