### ISSUE TITLE
Reverse for 'entry_page_serve_slug' not found

### ISSUE THREAD

**Issue by auvipy** [APSL/puput#191]
uring template rendering
In template /home/asif/upwork/mezprs/phoblog/puput/templates/puput/base.html, error at line 26

Reverse for 'entry_page_serve_slug' not found. 'entry_page_serve_slug' is not a valid view function or pattern name.

**Comment by MiltonLn** [comment]
Does it seem like you are reversing `entry_page_serve_slug` from your custom change for the base template?

Could you please elaborate a little bit more on this issue? maybe provide the actual source code from your `base.html` file around line 26.

Thanks!

**Comment by auvipy** [comment]
fixed in master
