### ISSUE TITLE
Native comments 

### ISSUE THREAD

**Issue by eskhool** [APSL/puput#193]
Hi Guys,
 What will be a recommended approach to add a native comment engine as an option?

Or maybe a new app called puput-comments for those cases where we want a built in comment engine instead of a social engine (like disqus/facebook etc.)

**Comment by MiltonLn** [comment]
I can think about a couple of options to handle this:

* A separated repo (`puput-comments`) to implement this and adding it with pip + INSTALLED_APPS
* A new app inside a `contrib` folder in the project with the models and code necessary to support this.

I like the second approach better. In any case, this should be an optional feature configurable through Django settings.

Are you interested in working on this? PRs are more than welcome :)

**Comment by eskhool** [comment]
If we do develop this, we will be happy to raise a PR for the same. I agree that the second approach makes more sense since on its own puput-comments does nothing.

**Comment by climu** [comment]
Just want to share my interest in this feature for [OpenStudyRoom](https://openstudyroom.org) website.

I don't have time to work on that but would definitely use it and be grateful if it get done.

**Comment by michalpleszczynski** [comment]
In my fork I added a possibility for new comments providers and added one that uses django-comments. If this is of interest to the project, comments are welcome on the PR #215
