### ISSUE TITLE
After creating a new page and child page and bog entry, error shown instead of the page.

### ISSUE THREAD

**Issue by auvipy** [APSL/puput#196]
Exception Type: NoReverseMatch at /pellet-pals-gunners-blg/hastan-rifle-review/
Exception Value: Reverse for 'entry_page_serve_slug' not found. 'entry_page_serve_slug' is not a valid view function or pattern name.

**Comment by bashu** [comment]
to @auvipy are you sure have installed and configured puput correctly? Please re-open issue, if it was not solved already
