### ISSUE TITLE
Internal server error when uploading pictures

### ISSUE THREAD

**Issue by ultimatesanjay** [APSL/puput#197]
Firstly, I would thank APSL for creating this amazing repository.

The problem is when uploading/searching pictures. Searching for images do not work. It gives me internal 500 server. Could you send me instructions on how to solve this?
Im a newbie to this. Thank you.

**Comment by marctc** [comment]
@ultimatesanjay please, paste here the full trace with the failure. Error 500 is too broad to see what happend

**Comment by ultimatesanjay** [comment]
Sorry, I'm quite new to this. Can you send me instruction on how to trace the failure?

Django | 2.2.1 
Python LSAPI | 1.4 
OpenLiteSpeed | 1.4.42 
acme.sh | 2.8.0
