### ISSUE TITLE
Remove google+ sharing button from pages

### ISSUE THREAD

**Issue by sakharovaan** [APSL/puput#202]
For example:
https://github.com/APSL/puput/blob/master/puput/templates/puput/entry_page.html#L77

Because it is closed, actually. When I'm trying to push this button, all I get is Google [apologies](https://plus.google.com/up/?continue=https://plus.google.com/share?url%3Dhttp://localhost:8080/2019/08/04/contacts/), because of Google+ network shutting down for consumers.

https://www.theguardian.com/technology/2019/feb/01/closure-google-plus-everything-you-need-to-know

**Comment by marctc** [comment]
Thanks for reporting @sakharovaan. Do you mind to create a PR to fix this?

**Comment by sakharovaan** [comment]
Excuse me, I didn't have time. I see that it was fixed yesterday.
