### ISSUE TITLE
Show category description

### ISSUE THREAD

**Issue by loleg** [APSL/puput#208]
Related to #34, it would be great to show the description field of the Category on the search result page. However, currently only the name of the category is accessible in the template via `entries_by_category` in [routes.py](https://github.com/APSL/puput/blob/f298f14428b62cc3b607115c706e219fb9a9345f/puput/routes.py#L41). While #94 contains basically a workaround to this, from a user perspective this seems overlooked and should be added to the route code.

**Comment by bashu** [comment]
to @loleg check #248
