### ISSUE TITLE
Extending Entry Page

### ISSUE THREAD

**Issue by sailorsamoor** [APSL/puput#209]
Hello. I tried to extend  Entry Page as it wrote in docs (add VideoUrl), all works, but I don't see the changes in Wagtail admin. May be good idea is add this lines into custom model?

> \# models.py of wagtail project:

> from puput.abstracts import EntryAbstract
> from wagtail.admin.edit_handlers import FieldPanel
> 
> class VideoEntryAbstract(EntryAbstract):
>     video_url = models.URLField(blank=True, null=True)
>     content_panels = EntryAbstract.content_panels + [
>         FieldPanel('video_url')
>     ]

**Comment by yedpodtrzitko** [comment]
hi,
did you follow the following steps in docs regarding [Registering Entry Extension](https://puput.readthedocs.io/en/latest/extending.html#registering-entry-extension) and running migrations?

**Comment by sailorsamoor** [comment]
Yes, I did, I quess that I hadn't new fields in Wagtail Admin seen. I did as I wrote - all works, thanks.

**Comment by yedpodtrzitko** [comment]
No problem. Would you mind closing the issue?
