### ISSUE TITLE
Create Entry bug

### ISSUE THREAD

**Issue by jonhairston** [APSL/puput#21]
The ability to create an entry page without being in the blog subtree breaks the relative url in the base template.

To reproduce create a child page underneath the root page and click entry. Entryt should not show up until you are in the blog subtree. Though I may be wrong on that assumption.

**Comment by marctc** [comment]
Hi @jonhairston,
Are you settings the blog as root page?

**Comment by jonhairston** [comment]
I am not. Does it need to be?

**Comment by marctc** [comment]
No, the only way that puput works properly is setting a Blog Page as a child of the root page. Are you doing in this ways?

**Comment by jonhairston** [comment]
Yes I am. The issue is that it is possible to create a Blog page without an Entry page.

**Comment by marctc** [comment]
I cannot reproduce the error. Have you extended the Entry Page model?

**Comment by jonhairston** [comment]
i have not. I can share the code with you via bitbucket if need be, its just for a personal project and nothing serious
