### ISSUE TITLE
2.7 support

### ISSUE THREAD

**Issue by pySilver** [APSL/puput#210]
Do we have any blockers for 2.7 support? Current setup requires:

```
'wagtail>=2.4,<2.7',
```

**Comment by Joaxin** [comment]
yes, we need this update.
![image](https://user-images.githubusercontent.com/8346164/69894621-14cbac80-135d-11ea-8796-fffbe7fcce2d.png)

**Comment by pySilver** [comment]
closing issue since patch is merged.
