### ISSUE TITLE
Django 3.0 support?

### ISSUE THREAD

**Issue by lanshark** [APSL/puput#218]
Any idea what needs done?  I may be willing to pitch in, but thought I would ask first.

**Comment by hellyworld** [comment]
This will be great!

**Comment by lanshark** [comment]
https://github.com/APSL/puput/pull/219

I had to drop support for python 3.5 (Django 3.x only supports 3.6+)

All tests pass, no other changes were required.

**Comment by marctc** [comment]
Did you do some manual testing?

**Comment by MiltonLn** [comment]
We really need to figure out a way to add automatic testing to the project, I didn't find Wagtail framework comfortable to do so, and the functional tests were too complex.

**Comment by lanshark** [comment]
I will be doing some manual testing as well, just need to get the test app running and give it a try

**Comment by lanshark** [comment]
I made the requested change, and updated the PR.  As far as I can determine, this is working.

**Comment by lanshark** [comment]
Thanks for merging that!
