### ISSUE TITLE
wagtail user bar prevents scrolling

### ISSUE THREAD

**Issue by jonhairston** [APSL/puput#22]
As the title states, whenever I am logged into the wagtail admin, and I'm looking at the blog I'm not allowed to scroll via mousewheel or arrowkeys. No problems if not logged in. could be a possible clash with my other js files

**Comment by marctc** [comment]
Hi @jonhairston,
I couldn't reproduce it. Can you attach an screenshot or explain me a little bit more how to reproduce it?

thanks!

**Comment by jonhairston** [comment]
I believe it may be a conflict with the pre-made theme I was using and the wagtail toolbar. So I guess its really a one time deal maybe. Once I find the library that's breaking things, I'll post results.
