### ISSUE TITLE
Translation files not compiled on pypi delivery

### ISSUE THREAD

**Issue by jbgury** [APSL/puput#226]
When using the installation from pip command : 
`pip install puput`
the component is installed succesfully, but the translation files are not compiled.
Using the puput apps into django causes that the default translation is displayed and there is no translation supported into templates or admin.
a workaround is to trigger the compilation of the translation files by browsing to the site-packages and call the django-admin command on the directory to compile all translation files.
`./django/bin/django-admin.py compilemessages`

I think that (as wagtail delivery) the translation messages should be compiled.

**Comment by bashu** [comment]
fixed in `develop` branch
