### ISSUE TITLE
Post-processing 'puput/css/bootstrap.min.css' failed!

### ISSUE THREAD

**Issue by Rsgm** [APSL/puput#23]
```
whitenoise.django.MissingFileError: The file 'puput/fonts/glyphicons-halflings-regular.eot' could not be found with <whitenoise.django.GzipManifestStaticFilesS
torage object at 0x7fe8d263a470>.
```

puput/fonts/glyphicons-halflings-regular.eot is not in the puput static files.
Could you please fix this?

**Comment by bashu** [comment]
+1

**Comment by jorgeluis11** [comment]
+1 !

**Comment by marctc** [comment]
@jorgeluis11 is still happening to you?

**Comment by gururajjeerge** [comment]
+1

**Comment by AkshJain99** [comment]
is there any solution to fix this issue?

**Comment by MiltonLn** [comment]
It is already fixed @AkshJain99 if you find it isn't please open a detailed issue so we can tackle it

**Comment by Maduflavins** [comment]
having same error
