### ISSUE TITLE
Ordered list is displayed without numbers.

### ISSUE THREAD

**Issue by Konstantin555** [APSL/puput#232]
Is it a bug or did I misconfigured something? 
In the editor I have ordered list:

![2020-10-12 16_46_02-Wagtail - Editing Entry_ New Article](https://user-images.githubusercontent.com/13664826/95753553-76151980-0caa-11eb-8f75-a4b1df0ffc05.png)

But it is displayed without numbers:

![изображение](https://user-images.githubusercontent.com/13664826/95753671-993fc900-0caa-11eb-8596-e5a689086a11.png)

puput==1.1.1
wagtail==2.10.2
Block responsible for the text:

```   
         <div class="post_body">
                <!-- POST TEXT  -->
                {{ self.body|safe }}
            </div>
```

In the browser the tag is `<ol>`

**Comment by Konstantin555** [comment]
Also tried it with `{{ self.body|richtext}}`

**Comment by CVYY39** [comment]
The numbers work fine on my install with Django 3.0.10, Wagtail 2.10.2, and Puput 1.1.1. Does the HTML output show the <ol><li> tags? If so, sounds like a CSS issue. I'm using a custom CSS so I'm not sure if the default one may have an issue.
