### ISSUE TITLE
Customize BlogPage Subpage Types

### ISSUE THREAD

**Issue by psyonara** [APSL/puput#237]
In the usecase of a single blog site (e.g. https://example.com/), one can currently have only entry pages. If I want to have different page types, e.g. Contact page, About page, etc, I believe this is not possible, because the `BlogPage` class restricts children to "EntryPage" only?

It would be nice to add to those subpage types in order to have other pages as children as well.

**Comment by CVYY39** [comment]
I worked around this by creating a new page type (which I called "RootPage") which does nothing but mirror the content of the blog. That allows other child pages (which I called "Information Pages"). It works well other than that you have to go to example.com/blog/ to add entries.

**Comment by bashu** [comment]
hey, @psyonara ! @CVYY39 is right, just create your own root / home page.
