### ISSUE TITLE
Update to Python3.9, Wagtail 2.9, Django 3.1?

### ISSUE THREAD

**Issue by krzysieqq** [APSL/puput#238]
Are there any plans for an update to Python3.9, Wagtail 2.9, Django 3.1?

**Comment by CVYY39** [comment]
I'm running Wagtail 2.11.2 without issue, at least. I can't recall exactly what I did but I followed the upgrade steps on their website.

**Comment by lanshark** [comment]
I am working on a PR for this now, actually.

**Comment by bashu** [comment]
to @krzysieqq  and @CVYY39  can you checkout `develop` branch and let me know if it was fixed or not
