### ISSUE TITLE
Trying out Puput and getting server errors and 404's on localhost

### ISSUE THREAD

**Issue by deronsizemore** [APSL/puput#24]
http://dpaste.com/03N6HM3

You can see the errors I'm getting above. I'm able to access the blog_admin no problem but depending on what I click on, I seem to be getting random errors where nothing works until I re-run server. I also am not able to access /blog/. I continue to receive 404's:

    Request URL:	http://127.0.0.1:8000/blog/
    Raised by:	wagtail.wagtailcore.views.serve

Anyone have any idea on why I'm getting these things? Everything appears to be installed correctly. I followed the stand alone installation since I just wanted to add this to my existing install.

**Comment by eduherraiz** [comment]
It seems a problem trying connect to the database.
Could you share your configuration?

**Comment by deronsizemore** [comment]
Hey, sorry for the delay. I think I figured this out. This same thing happened actually after removing Puput from my install so that got me digging further (as I first assumed it was Puput). I think it was a local memory debugger which I had installed to test some things called pympler. Once I disabled that application things are working fine out.

Sorry about the false alarm.
