### ISSUE TITLE
How to insert Code Snippet?

### ISSUE THREAD

**Issue by VadymKhodak** [APSL/puput#240]
I'm sorry for bothering you.
But I can't find a way to insert code snippets to blog text.
Is anyone here who can help me?

**Comment by CVYY39** [comment]
You can format text as code with the third button in from the left side of the toolbar on the rich text editor. 

That said, I don't know whether it supports syntax highlighting without jumping through some hoops.

**Comment by VadymKhodak** [comment]
Thank you so much!
I want to find a solution to have highlighted code snippet.
Like that
![image](https://user-images.githubusercontent.com/32848370/113513341-f3db2300-9571-11eb-9af8-0ed60e907bcd.png)

**Comment by Pei2tech** [comment]
`$ form 
  x += 1
`

**Comment by Pei2tech** [comment]
The wagtail-markdown can reach your requirement. please refer to the link: https://github.com/torchbox/wagtail-markdown.  After installing wagtail-markdown, you need to modify templates and follow the instruction to add Abstract base classes.
