### ISSUE TITLE
Latest version puput=1.1.1 is not compatible with (Upgraded) Django=3.2.4 (LTS)

### ISSUE THREAD

**Issue by prakash243** [APSL/puput#241]
puput 1.1.1 requires Django<3.1,>=2.1.6, but you have django 3.2.4 which is incompatible.

**Comment by mirzadelic** [comment]
Any news on this?

**Comment by eskhool** [comment]
> Any news on this?

Yeah, some news would be nice. Even if just to say, not til XYZ date :)

**Comment by marctc** [comment]
Hey. I'm not actively maintaining this repo anymore. Please feel free to open pull requests and I will merge and release new versions.

**Comment by bashu** [comment]
to @prakash243  and @eskhool  can you checkout `develop` branch and let me know if it was fixed or not
