### ISSUE TITLE
How to add table block?

### ISSUE THREAD

**Issue by jefcolbi** [APSL/puput#243]
Hi,
Sorry to bother you, but i can find a way to add a Table block to puput editor.
Thanks for you patience

**Comment by Konstantin555** [comment]
Bump.
Any ideas on how to add the Wagtail's TableBlock into puput?

**Comment by csalom** [comment]
Sorry, it's too late, I know... but I'm cleaning all the issues that I can now.

You'll need to extend blog or entrypage to add an streamfield where to use wagtail's TableBlock and will be able to use on your new templates.
