### ISSUE TITLE
Upload 1.1.2 on PyPI

### ISSUE THREAD

**Issue by bashu** [APSL/puput#249]
Hey @marctc 

I don't have access to upload package on  PyPI, can  you fix that? Just in case my pypi username: bashu

**Comment by bashu** [comment]
cc @marctc @aaloy

**Comment by marctc** [comment]
Got it, will do it later

**Comment by marctc** [comment]
Done! (BTW, we should start using poetry to replace the setup.py)

**Comment by bashu** [comment]
to @marctc we will once I fix test suite
