### ISSUE TITLE
Partially working '/blog_admin' page

### ISSUE THREAD

**Issue by tian-yan** [APSL/puput#256]
I have a fresh deployment of puput on top of a fresh Django project.
`example.com/blog/` and `example/blog_admin/` are all working fine.  However, I realize below page is partially working.
when I click on **`ROLES`** button, or the **`upper arrow`** at the left-bottom corner to change user settings, nothing happens, it does not takes me to any page. 
![image](https://user-images.githubusercontent.com/28975592/150289611-dabb98d4-4637-43ff-9b36-bfee56dce02b.png)

Also, button **`PROMOTE`**, **`SETTINGS`**, **`ADD CATEGORIES`** in below page are not working at all.
![image](https://user-images.githubusercontent.com/28975592/150290586-85accbcf-c9aa-4234-87c8-586de6895b1c.png)

Any advise please ?

**Comment by tian-yan** [comment]
I managed to fix this myself. It was my problem, I did not provide a comprehensive list of Static files required. 
I did a static file collection by command **`python manage.py collectstaticfiles`**, and then copied all collected static files over to NGINX server. Now everything works fine.

**Comment by bashu** [comment]
to @tian-yan don't give up, you will make it!
