### ISSUE TITLE
Expected UI issues with Wagtail 3.0 release

### ISSUE THREAD

**Issue by thibaudcolas** [APSL/puput#259]
The [Wagtail 3.0 first release candidate](https://github.com/wagtail/wagtail/discussions/8362) is out. There are large UI changes in this release, for which we have [reviewed expected breakage in third-party UI customisations](https://github.com/wagtail/wagtail/discussions/7739#discussioncomment-2615089).

This is beyond what we do with our normal breaking changes policy, since the majority of those changes are on parts of Wagtail that haven’t been publicly supported / documented in any way. To make sure this goes smoothly anyway, I’m here to provide an advance notice of what we’re aware of with this specific package 🙂 

In the case of Puput there is only one change we’re expecting to require rework for Wagtail 3.0.

## Uppercase text

The majority of the Wagtail admin UI [no longer uses uppercase text](https://github.com/wagtail/wagtail/issues/7624), to improve readability. The exception is the page status (live, draft, etc.). Suggested actions:

- Remove all usage of uppercase text in the CMS, except for page status.
- Aside from CSS, the utility classes `u-text-transform-uppercase` and `label-uppercase` no longer exist and shouldn’t be used anymore.

Here is the one match in this repository:

```text
wagtail/APSL/puput/puput/static/puput/css/puput.css
151:  text-transform: uppercase;
```

---

I hope this all makes sense. We’ve made a lot of other styling and template changes that are hard to track down, and for which it’s unclear whether any breakage might be expected or not. As you go through the Wagtail 3.0 compatibility work, please let me know if there are other compatibility issues you come across so we can consider those customisations in Wagtail development in the future, and let others know about those breakages.

**Comment by csalom** [comment]
Hello!
As this static file is not being used in the Wagtail Admin, we won't delete the uppercase.

Thank you for the suggestion :smile:
