### ISSUE TITLE
How to uninstall puput and use plain wagtail without loosing content

### ISSUE THREAD

**Issue by sebastian-muthwill** [APSL/puput#260]
Is there a way to uninstall puput but stay with wagtail and not loose the content?

**Comment by CVYY39** [comment]
What exactly are you trying to do? Have the content remain exactly as-is on the site? Easiest way to do that would probably be to convert it to static HTML.

**Comment by sebastian-muthwill** [comment]
I was trying to uninstall puput but keep wagtail with the content. 
But that was a wrong path I went down. Never mind. Will close the issue.
