### ISSUE TITLE
Any update comming for v4.1 LTS

### ISSUE THREAD

**Issue by codesardine** [APSL/puput#262]
I have been waiting for an update since 3.0 come out, is this project abandoned?

**Comment by marctc** [comment]
@codesardine I'm not mantain this project anymore but I'm happy to merge any new contributions
and push new releases. @bashu do you wanna take a look at this?

**Comment by bashu** [comment]
to @marctc yes, I will

**Comment by codesardine** [comment]
I don't have alot of experience with django, but I am happy to help.

**Comment by csalom** [comment]
Hello @bashu,
Have you been able to do something about the update?
We plan to work on puput during the following weeks and we can work with the update of wagtail and checking that everything is working fine.

**Comment by codesardine** [comment]
Hi @csalom,
I have test it and can confirm that is working up to version 4.0

**Comment by csalom** [comment]
Hey @codesardine,
Glad to hear it. I've released on Friday a version wtih wagtail4 support and dropping support to < 3: https://github.com/APSL/puput/releases/tag/1.2.0
