### ISSUE TITLE
django-endless-pagination abandoned, switch to django-el-pagination

### ISSUE THREAD

**Issue by nicklo** [APSL/puput#27]
Apparently django-endless-pagination has been abandoned and fails in django >= 1.9: 

https://github.com/frankban/django-endless-pagination/issues/92

Are there any plans to switch to django-el-pagination?

https://github.com/shtalinberg/django-el-pagination

**Comment by nicklo** [comment]
I've added a pull request albeit admittedly minimally tested: https://github.com/APSL/puput/pull/28

**Comment by marctc** [comment]
> Apparently django-endless-pagination has been abandoned and fails in django >= 1.9:!
 I realized that django-endless-pagination won't be supported anymore, so any alternative sounds good to me.
> Are there any plans to switch to django-el-pagination?
absolutely!
