### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by kevinrenskers** [APSL/puput#271]
There's some good stuff in the unreleased section of the changelog. When can we expect a new release?

**Comment by banagale** [comment]
Also curious about this. Direct link to the [unreleased section](https://github.com/APSL/puput/blob/master/CHANGELOG.md#unreleased) of the changelog.

Is it correct that the current release of puput won't run under 3.11?

**Comment by tecbr** [comment]
[Django 4.2 released](https://www.djangoproject.com/weblog/2023/apr/03/django-42-released/) (LTS).

**Comment by csalom2x2** [comment]
Hi!
We will be working adding support to new versions on the following days.
@banagale related to 3.11 question, we haven't tested the previous version with Python 3.11, feel free to do it

**Comment by vbabiy** [comment]
@jlmirocoll any update here?

**Comment by csalom** [comment]
Hi, we will try to do it asap, as wagtail5 and django 4.2 have been alredy merged.

**Comment by AlanSwenson** [comment]
Cant wait for the next release!

**Comment by csalom** [comment]
Finally done: https://github.com/APSL/puput/releases/tag/2.0.0
