### ISSUE TITLE
Setup instructions suggest use of deprecated wagtail middleware

### ISSUE THREAD

**Issue by banagale** [APSL/puput#283]
The setup docs ask for the following to be added to `settings.py`

```
MIDDLEWARE_CLASSES = (
    ...
    'wagtail.core.middleware.SiteMiddleware',
    'wagtail.contrib.redirects.middleware.RedirectMiddleware',
)
```

The first middleware recommended is deprecated. I suspect this is just outdated docs, because the replacement way to get at `Site`, `from wagtail.core.models import Site` is used a few times in the package.

Also, should this be updated to suggest the redirect middleware be added to `MIDDLEWARE`?  Use of `MIDDLEWARE_CLASSES` conflicts with django debug toolbar.

**Comment by csalom** [comment]
It's updated on the last releases. Read the docs will be updated as soon as possible. Thanks
