### ISSUE TITLE
Remove date from URL

### ISSUE THREAD

**Issue by carltongibson** [APSL/puput#32]
I'd like to serve posts without the date in the URL. Something like:

```
    url(
        regex=r'^(?P<blog_slug>[-\w]+)/(?P<slug>[-\w]+)/$',
        view=EntryPageServe.as_view(),
        name='entry_age_serve_slug_only'
    )
```

I add this and adjust `EntryPageServe` and `BlogRoutes` etc but I keep getting a 404. 

~~What am I missing? How can I get the URL to serve the matching Entry?~~

Thanks.

**Comment by carltongibson** [comment]
My 404s were caused by an incorrect `blog_slug` 😳

**Comment by sirrryankennedy** [comment]
I did the same thing, but I can't seem to figure out how to change the urls in "Latest Entries" sidebar element. In tags/categories_list.html, I see `{% routablepageurl blog_page "entries_by_category" category.slug %}` but not sure how to edit it exactly. Any thoughts?

**Comment by robnardo** [comment]
Hi @carltongibson - i am having trouble removing the date in the URL - changing the links on Puput from /blog/2018/10/23/my-post-slug to /blog/my-post-slug  i was wondering if you could please help?  What are all the changes to make this happen?

**Comment by robnardo** [comment]
@carltongibson - no worries.. i figured it out.. i changed <blog_slug> to <blog_path> in your code.  seems to work now.
