### ISSUE TITLE
Substitute Category model

### ISSUE THREAD

**Issue by fab10m** [APSL/puput#34]
Hi,

is there anyway substitute the puput category model with a custom one? 
I'm trying to install puput over an existing django project. All has gone very well, but my project already has his own category model that can't be substitute.

Best,

Fabio

**Comment by marctc** [comment]
Yeah, It can be done without many problems. However, you have to consider that you will need to modify the default templates and the entries filters in routers.py

**Comment by fab10m** [comment]
Thanks for your prompt reply!
So, in order leave the snippet category as in puput, but pointing to "my" category, I only need to modify:
- routers.py (where?)
- default templates (which one?)
- models.CategoryEntryPage?

Best,
Fabio

**Comment by marctc** [comment]
>routes.py (where?)

```python
   @route(r'^category/(?P<category>[-\w]+)/$')
    def entries_by_category(self, request, category, *args, **kwargs):
        self.search_type = _('category')
        self.search_term = category
        self.entries = self.get_entries().filter(entry_categories__category__slug=category)
        return Page.serve(self, request, *args, **kwargs)
```
>default templates (which one?)

`templates/puput/tags/categories_list.html`

>models.CategoryEntryPage?

```python
class CategoryEntryPage(models.Model):
    category = models.ForeignKey(Category, related_name="+", verbose_name=_('Category'))
```

**Comment by fab10m** [comment]
Thank you very much Marc!
Do you plan to make the category customizable by the developers without edit your core code?

Fabio

**Comment by marctc** [comment]
Yeah, why not? I have to study this feature and implement it in the cleaner way.

**Comment by fab10m** [comment]
Great! I stay tuned then :-)

**Comment by fab10m** [comment]
Hi Marc,

I made the following patches and anything seems to work:
- I create an entry for the setings.py file PUPUT_CATEGORY_MODEL;
- I commented the statement @register_snippet over the "Category" definition;
- I changed the name of Category in CategoryDefault
- I added this code under CategoryDefault definition

```python
CategoryModel = import_model(getattr(settings, 'PUPUT_CATEGORY_MODEL', CategoryDefault))

@register_snippet
class Category(CategoryModel):
    objects = CategoryManager()

    class Meta:
        proxy = True

```
- I made the following change the categories_list inclusion_tag (because I don't need nested Categories)
```python
        if hasattr(Category, 'parent'):
            categories = Category.objects.with_uses(blog_page).filter(parent=None)
        else:
            categories = Category.objects.with_uses(blog_page).all()

```

Do you have any kind of suggestions?

Fabio

**Comment by marctc** [comment]
> I create an entry for the setings.py file PUPUT_CATEGORY_MODEL;

:+1: 
>I made the following patches and anything seems to work:
- I create an entry for the setings.py file PUPUT_CATEGORY_MODEL;
- I commented the statement @register_snippet over the "Category" definition;
- I changed the name of Category in CategoryDefault
- I added this code under CategoryDefault definition

Nice approach, but I think it will be better a pattern like `EntryAbstract`. You can define the default Category model in abstracts and define the actual Category in models.py like EntryPage.
>- I made the following change the categories_list inclusion_tag (because I don't need nested Categories)

:+1:

**Comment by fab10m** [comment]
Thanks Mark! 
I'm going to try to follow the approach suggested by you.

**Comment by marctc** [comment]
@fab10m any news regarding this issue?

**Comment by fab10m** [comment]
Hi, @marctc I've no news. I'm stiill in the same situation of 5 months ago. Allora works fine, so I decided not to touch anything :-)
