### ISSUE TITLE
Improper construction of urls for entries

### ISSUE THREAD

**Issue by Nekmo** [APSL/puput#35]
When I use the "LIVE" button from the administration Puput, opens the correct url:
http://my.dev:8001/en/esto-es-una-prueba-de-blog/una-pagina-del-blog/

But if I'm looking at the index of the blog, the url is incorrect and returns a 404 error:
http://my.dev:8001/en/esto-es-una-prueba-de-blog/2016/03/14/una-pagina-del-blog/

![instantanea7](https://cloud.githubusercontent.com/assets/740106/13753002/7970c3f6-ea11-11e5-8154-3f45f8a42f24.png)

![instantanea7](https://cloud.githubusercontent.com/assets/740106/13753021/918d93b0-ea11-11e5-85c6-bcff93ee380a.png)

**Comment by marctc** [comment]
Hi,
Try to set your site root to your blog page as is explained on the docs:
http://puput.readthedocs.org/en/latest/sites.html

BTW,  did you set the puput urls with i18n patterns?

**Comment by Nekmo** [comment]
Yes, I have placed inside the i18n.

Is this a problem?

**Comment by Nekmo** [comment]
I tried putting Puput outside the i18n_patterns and works fine. However, I would like to use i18n_patterns.

**Comment by marctc** [comment]
Hi, 
Have you tried that i told you on my first reply?

**Comment by Nekmo** [comment]
Yes. This is my root website:
![instantanea7](https://cloud.githubusercontent.com/assets/740106/13820249/c4a86b1c-eb9c-11e5-82bb-b185c32bfa43.png)

My blog is inside this website root:
![instantanea7](https://cloud.githubusercontent.com/assets/740106/13820273/e47d68ca-eb9c-11e5-9cdf-d3813ccc71d3.png)

And finally my post:
![instantanea7](https://cloud.githubusercontent.com/assets/740106/13820288/faaa5c52-eb9c-11e5-955f-e1d6f93fa98c.png)

Root is properly configured:
![instantanea7](https://cloud.githubusercontent.com/assets/740106/13820317/1d9cf1a2-eb9d-11e5-8a14-0f5ccedc9418.png)

**Comment by marctc** [comment]
Hi,

If you set the Blog as a child of "Mi sitio" and under i18n url patterns it doesn't work. I18n patterns and a Puput blog will work if you set as Root Page your Blog Page instead "Mi sitio".
