### ISSUE TITLE
Have a how to contrib

### ISSUE THREAD

**Issue by voylinux** [APSL/puput#36]
As this is originally prepared to be installed with pip, it would be nice to have small document file to explain how to setup a develpment enviroment to work on puput improvement without installing it, from source code.

**Comment by voylinux** [comment]
I think I am doing this in a very hacky way right now, having the cloned repo in another folder and a symbolic link inside a wagtail project.

Which is the best aproach for that?

**Comment by marctc** [comment]
Yeah, this is correct. You also can go to repo folder and peform `pip install -e .` within your virtualenv. So any change on your Puput cloned repo will be avaiable on your Wagtail project.

**Comment by voylinux** [comment]
Nice. That will help.
