### ISSUE TITLE
Add support for other comment systems

### ISSUE THREAD

**Issue by marctc** [APSL/puput#39]
It would be interesting to have support for other comment systems like Facebook comments. Before that the following things are needed:

- [x] Remove tapioca-disqus from setup.py
- [x] Refactor `EntryPageUpdateCommentsView` to suport other comment systems
- [x] Refactor js code that update the number of comments of an entry.

**Comment by voylinux** [comment]
Can you define priorities on wich systems you would like to include. Some of them may be harder than others.

**Comment by marctc** [comment]
Maybe facebook comments. I think is widely used too.

**Comment by voylinux** [comment]
I deactivated my Facebook account last week but yes, that looks like a good idea.

**Comment by voylinux** [comment]
Looks that maybe for Facebook you just need some kind of selector to activate and then...
[https://www.allaboutghost.com/how-to-add-facebook-comments-to-ghost/](https://www.allaboutghost.com/how-to-add-facebook-comments-to-ghost/)

**Comment by Juanlu001** [comment]
May I add another comment system: https://github.com/posativ/isso which apparently is used by another guy in Mallorca, @somenxavier :)

**Comment by somenxavier** [comment]
@Juanlu001 Who are you? Do I know you? ;-)

**Comment by Juanlu001** [comment]
I don't think so, but I saw your website listed on some isso website and found it curious that you live in Mallorca too. Didn't want to bother you :)

**Comment by marctc** [comment]
Thanks @Juanlu001. It seems cool. I'll take a look!

**Comment by somenxavier** [comment]
@Juanlu001 Don't bother.
@all: this [wiki](https://github.com/posativ/isso/wiki/Powered-by-isso) has a list of website powered by isso. When @Juanlu001 get one, please add it up ;-)
