### ISSUE TITLE
Suggestion Add to document

### ISSUE THREAD

**Issue by taedori81** [APSL/puput#4]
First Thanks for the good blog app.
As recommendation, why don' you add this to setup - wagtail blog app section

"Add this to Installed_apps section"
    'wagtail.contrib.wagtailsitemaps',
    'wagtail.contrib.wagtailroutablepage',

because even though using wagtail, it isn't there by default. So We have to add them manually( I think :) )
Without them, I got errors that say " Wagtailroutablepage_tags error.."

If I am wrong, just ignore this.

**Comment by marctc** [comment]
Thanks @taedori81. You are right, it isn't in the wagtail documentation by default. Can you add it to readme.rst and setup.rst and make a PR with this changes?
cheers!
