### ISSUE TITLE
Body content as StreamField

### ISSUE THREAD

**Issue by iampbernardo** [APSL/puput#40]
Maybe the WordPress way is not the best way, but I think some of the WordPress options to create diferent kind of posts is a very good idea.

Something like 
![custom_post_types](https://cloud.githubusercontent.com/assets/1538304/13907973/ee59d530-eef9-11e5-9e2c-71b380537bac.png)

What do you think about that. Is it too opinionated aproach?.
Should those be pluggins?

**Comment by marctc** [comment]
I'm working on a similar approach. We use Puput in APSL's blog but we have the problem that the default RichTextField don't work well for other things like inserting code snippets. We though an interesting approach would be replace the body field from a RichTextField to a StreamField (see this link http://thirdworldnomad.com/2015/06/22/developing-wagtail on the section "Extending StreamField Block").

**Comment by voylinux** [comment]
Looks like a great aproach.
Then this library could also help with syntax highlighting [http://prismjs.com/](http://prismjs.com/)

The main problem would be migrating already exiting posts, right?

**Comment by marctc** [comment]
Yes, it is. For the moment, I think that the best option is have two body fields and provide to user a tool to migrate between fields (something like this http://docs.wagtail.io/en/v1.4.1/topics/streamfield.html?highlight=streamfield#migrating-richtextfields-to-streamfield=

**Comment by mronoffon** [comment]
what is the status of the 'RichTextField to a StreamField' (if there is one)?

**Comment by marctc** [comment]
Hi @mronoffon,
I've waiting if [wagtail-markdown](https://github.com/torchbox/wagtail-markdown) make any progress to be production ready.

There are a [branch](https://github.com/APSL/puput/tree/body_streams) for this goal. Feel free to try it.

**Comment by FlipperPA** [comment]
Howdy @marctc, thanks for your efforts! I have a pretty good generic StreamField body block I've developed. Want me to implement a version and issue a PR? Perhaps as a different Entry page type, maybe a "StreamEntry"?

**Comment by mronoffon** [comment]
YES, pleas!!!

**Comment by marctc** [comment]
> Howdy @marctc, thanks for your efforts! I have a pretty good generic StreamField body block I've developed. Want me to implement a version and issue a PR?

Yeah, sounds good to me. What do you have in mind?

> Perhaps as a different Entry page type, maybe a "StreamEntry"?

I would rather implement as an extra body field in Entry model and set the `body` field as `blank=True`

**Comment by mronoffon** [comment]
any headway?

**Comment by marctc** [comment]
We are working on it in this PR: https://github.com/APSL/puput/pull/83

**Comment by FlipperPA** [comment]
Feel free to help out with the PR if anyone would like! I'm hoping to get some time soon to merge the best from both branches.

**Comment by MiltonLn** [comment]
Please see pull request #112

**Comment by albcunha** [comment]
Guys, I made a symbolic bountysource for this feature. Not a lot, 50 bucks, but better than nothing, right? Keep up the good work!

**Comment by marctc** [comment]
Awesome!!! Thank you very much @albcunha. Never heard about this. @MiltonLn @FlipperPA can you take a look?

**Comment by sabueso** [comment]
@albcunha is there some possibility to increase those 50 bucks with money from other users? I'll be grateful to contribute ;)

**Comment by marctc** [comment]
@sabueso Yep!
https://www.bountysource.com/issues/32083681-body-content-as-streamfield

**Comment by sabueso** [comment]
@marctc Done!

**Comment by marctc** [comment]
awesome!

**Comment by marctc** [comment]
@albcunha @sabueso it seems that with new wagtail editor this issue won't need to develop. We appreciate your economical effort, but maybe it will fair if nobody earns that money. What do you think?

**Comment by FlipperPA** [comment]
What still needs doing here? I thought it was mostly complete, but its honestly been quite a while now and would probably need some tweaks for Wagtail 2.0. :)

**Comment by MiltonLn** [comment]
@FlipperPA, we are just going to support wagtail 2.0 to use draftail, that would solve all of our needs, I'm taking care of that this week

**Comment by albcunha** [comment]
I think my share can be donated to you. After all, you deserve free beer on the house!

**Comment by FlipperPA** [comment]
@MiltonLn Right on, good to hear! I'm sticking with the structured content approach of StreamField with Peregrine, so that'll be a nice differentiation.

**Comment by marctc** [comment]
@FlipperPA can you show us a screenshot of how it looks?

**Comment by FlipperPA** [comment]
Sure! Here's the site: https://PyPhilly.org/ The ABOUT page has an image header example. It's running entirely Wagtail 2 on Django 2. The backend is using Zappa to run on AWS Lambda serverless with SQLite on S3. Total cost: $0.56 to host last month! :)

And here's the editor:

![peregrine-page-editor](https://user-images.githubusercontent.com/68164/37055869-cd37dcea-2150-11e8-897c-927f64ce56a1.png)

**Comment by marctc** [comment]
@albcunha @sabueso do you think that the options that draftail provide by default (https://springload.github.io/draftail/) is enough or we need something special?

**Comment by albcunha** [comment]
I agrree with Milton regarding highlighted code. The alternative given by Flipper Works great as well. But there's a dealbreaker for me. Sometimes I embed iframes. Would it be difficult to allow it to edit the HTML source code?

**Comment by albcunha** [comment]
I agrree with Milton regarding highlighted code. The alternative given by Flipper Works great as well. But there's a dealbreaker for me. Sometimes I embed iframes. Would it be difficult to allow it to edit the HTML source code?

**Comment by FlipperPA** [comment]
That's a tricky one, especially with Draftail as there is not HTML stored in the database. It stored the whole editor area as JSON, which is rendered to HTML on demand. It might be necessary to create some sort of IFRAME or RAW HTML button for those cases, that just renders whatever you put into the field exactly as it appears.

**Comment by MiltonLn** [comment]
I agree with @FlipperPA, Is also worth saying that kind of feature is away the scope of this project, maybe that can be better handled directly on Wagtail project.

**Comment by MiltonLn** [comment]
Closing this because we are now supporting Wagtail 2.0 and its cool Draftail editor, please reopen if something different is needed.
