### ISSUE TITLE
Custom JS includes

### ISSUE THREAD

**Issue by voylinux** [APSL/puput#43]
I will work on this one as we talked, but put it here to have it tracked in the main repo if you are planning to include it in core.

The idea behind this is leaving blog admins to include JS code with is not hard-coded in templates like analytics or other tracking code.

**Comment by voylinux** [comment]
I was thinking about opening a new "folder" in sidebar to put a "custom" section for this kind of customizations. Do you see it?

**Comment by marctc** [comment]
Now is on Settings tab. Could be good separate all this content in a new tab. Sure!

**Comment by voylinux** [comment]
Yeah!. We can open this new section for those things.
