### ISSUE TITLE
Add category in insert post page

### ISSUE THREAD

**Issue by eduherraiz** [APSL/puput#47]
We can choose the category of a post from their insert page, but we can't add a new category.
I think it could be useful.

**Comment by marctc** [comment]
Related https://github.com/wagtail/wagtail/pull/3305

**Comment by marctc** [comment]
This issue should be addressed to Wagtail team. They added a new M2M field (https://github.com/wagtail/wagtail/pull/3305) in their last release but not the ability to add new items.

**Comment by Jeanluis019** [comment]
@marctc the issue referenced is closed is that option coming in the future?, or how can I implement it myself?, I accept suggestions.
