### ISSUE TITLE
Changing the Username to display the full_name

### ISSUE THREAD

**Issue by xpostudio4** [APSL/puput#48]
I am not sure this can be called an issue but what is the simplest way to change the owner field to display the full name of the user instead of his username?
![3c1dd1c4-0307-11e6-88d3-b1d83a0b3f8d](https://cloud.githubusercontent.com/assets/755375/14574340/19c9bdbe-0329-11e6-8350-8b1b5bbeae09.png)

**Comment by marctc** [comment]
The editor's admin is entirely developed by the Wagtail team so I can't tell how to customize that in a proper way. Maybe your can extend the Django User model and overwrite the __unicode__/__str__ magic methods to display the full_name instead the username

**Comment by xpostudio4** [comment]
Thank you @marctc the correct way to handle that is to overwrite the User `__str__` method as below in an admin.py file:

``` 
from django.contrib import admin
from django.contrib.auth.models import User

def str_function(self):
    return self.get_full_name()

User.__str__ = str_function
User._meta.ordering = ('first_name', 'last_name')

admin.site.unregister(User)
admin.site.register(User)
```

I left this here for future reference.

**Comment by marctc** [comment]
thanks!
