### ISSUE TITLE
Header Image not saving

### ISSUE THREAD

**Issue by mronoffon** [APSL/puput#61]
Saving 'normal' images (wagtailimages.Image) is no problem, but when i use 
WAGTAILIMAGES_IMAGE_MODEL ("core.APPImage" - mine), I get the following error: "Select a 
valid choice. That choice is not one of the available choices." The code originates from the 
example, so there "shouldn't" be any syntax errors. Im using wagtail 1.5.3, with django 1.9.9.

Thanks in advance

**Comment by marctc** [comment]
@mronoffon you can close this https://github.com/torchbox/wagtail/issues/2911
