### ISSUE TITLE
author username

### ISSUE THREAD

**Issue by fab10m** [APSL/puput#62]
Hi Marc,

why I'm not able to to point to author page when the author name contains the "." or the "@"? This is the pattern I'm using for the author pages 
```python
@route(r'^author/(?P<author>[\w.@-]+)/$')
```
Regards,

Fabio

**Comment by marctc** [comment]
It seems a Wagtail limitation since the regex for serving pages is `'^([\w\-/]*)$'`.

**Comment by fab10m** [comment]
Thank you very much March for your quick reply.

Regards,

Fabio

2016-08-18 16:08 GMT+02:00 Marc Tudurí <notifications@github.com>:
