### ISSUE TITLE
How to change base blog template?

### ISSUE THREAD

**Issue by nux17** [APSL/puput#63]
Hello,

I can't find anything in the doc to change puput's default base template (colors, etc)...

How can I do such thing?

**Comment by JuanjoA** [comment]
To inherit puput templates on a wagtail project I use:

1/ create template for home: 
myproject/myproject/templates/puput/blog_page.html

2/ create template for entry detail:
myproject/myproject/templates/puput/entry_page.html


Maybe you can edit templatetags also:

myproject/myproject/templates/puput/tags/entries_list.html
(lastest and popular entries)


myproject/myproject/templates/puput/tags/entries_list.html
(recent and popular entries)

JJ

**Comment by marctc** [comment]
Hi @nux17, @JuanjoA  is on the right way (thanks!)

**Comment by nux17** [comment]
@JuanjoA Thank you!

So, I've to create a puput folder in my templates folder and copy the puput base templates and change it?

What about the CSS?

Moreover, what's the difference between blog_page and entry_page?

Thanks for helping.

**Comment by marctc** [comment]
> So, I've to create a puput folder in my templates folder and copy the puput base templates and change it?

Yes.

>What about the CSS?

You have to do the same procedure that @JuanjoA explained to you.

>Moreover, what's the difference between blog_page and entry_page?

`blog_page` is the template of the blog home page and `entry_page` is the template of the detail of an entry.

**Comment by nux17** [comment]
Thanks for all the explainations, you guys rock!

Hope that will help other people too :)
