### ISSUE TITLE
How to integrate with wagtail and create a web portal

### ISSUE THREAD

**Issue by JuanjoA** [APSL/puput#65]
Hello, I trying to integrate wagtail and puput to create a web cms portal.
As puput take control over cms, which it's the recommended way to integrate other pages, different from blog_page and entry_page?

Example:
I have a home with multiple tags (recent entries, popular entries, advertisement, ...) and header, footer, . . ., and need to create some menu entries , to new page models, etc.
Home -> puput blog_page
When I click over a post --> puput entry_page
New pages needed: forms, other page models, ...

Thx

**Comment by marctc** [comment]
Hi,

> As puput take control over cms, which it's the recommended way to integrate other pages, different from blog_page and entry_page?

No, puput won't take control over cms, simply adds new models, templates and a different url format (only for entries). 

You can create new models, forms, templates or whatever your want but in another Django app. Wagtail will register this models too and you will be able to structure your portal as you wish

There you have an example  of a project with puput and wagtail :
https://www.ncora.com/

**Comment by JuanjoA** [comment]
Thanks @marctc !
I can move blog_page under home page and create all correctly.
Now, to show on home some entries, I need to use puput tags, but the context is not correct (i.e recent_entries search for blog_page and home is page) but this is another history.
To solve this, I can create my own tags and adapt them.
Thanks again.

**Comment by marctc** [comment]
You wellcome!

**Comment by hazho** [comment]
thanks for this awesome topic, can you share Steps please????
