### ISSUE TITLE
installation flow in setup.rst

### ISSUE THREAD

**Issue by emdete** [APSL/puput#67]
i followed the docs/setup.rst (after a `virtualenv -p /usr/bin/python3 env; source ./env/bin/activate; pip install django; django-admin.py startproject demo`) line by line. when doing the `demo/manage.py migrate` (and setting PROJECT_ROOT as requested) (and fixing the error `django.core.exceptions.ImproperlyConfigured: COMPRESS_ROOT defaults to STATIC_ROOT, please define either`)  i get a:

```
 WARNINGS:
 ?: (1_8.W001) The standalone TEMPLATE_* settings were deprecated in Django 1.8 and the TEMPLATES dictionary takes precedence. You must put the values of the following settings into your default TEMPLATES dict: TEMPLATE_CONTEXT_PROCESSORS.
```

when requesting i get an error:

```
 AttributeError: 'WSGIRequest' object has no attribute 'user'
```

is the setup document uptodate and meant to work out of the box?

**Comment by emdete** [comment]
ok, that one (no attribute user) is fixed, one has to change MIDDLEWARE to MIDDLEWARE_CLASSES... i do not know why that is not generated correctly.

the warning persistst and i get another warning:

```
RemovedInWagtail17Warning: Using a tuple for search_fields on Page subclasses is deprecated, use a list instead
  index.FilterField('page_ptr_id')
```

**Comment by emdete** [comment]
and i've overseen this one:

```
Warning: django.conf.urls.patterns() is deprecated and will be removed in Django 1.10. Update your urlpatterns to be a list of django.conf.urls.url() instances instead.
  urlpatterns += patterns('', (r'^favicon\.ico$', RedirectView.as_view(url=settings.STATIC_URL + 'myapp/images/favicon.ico')))
```

could be corrected in the doc as well.

**Comment by marctc** [comment]
Are you using Django 1.10, right?

**Comment by emdete** [comment]
i installed via pip, looking into `lib/python3.5/site-packages/django/__init__.py` shows `VERSION = (1, 9, 10, 'final', 0)`. so no, it's 1.9, right?

what is the desired django version for puput? isn't it 1.9 and if so why is 1.9 installed?

**Comment by emdete** [comment]
i was asked to issue a `demo/manage.py makemigrations` as well, shouldn't that be in the flow as well (with some explanation)?

finally the link "Continue reading »" points to a wrong location (i have a setup where django is in a sub-path "/PATH_PREFIX/blog/..." only so i have `url(r'^{}'.format(settings.PATH_PREFIX), include('puput.urls')),`) the `PATH_PREFIX` part is dublicated. haven't figured out what's wrong in my setup (or if its a bug).

**Comment by marctc** [comment]
@emdete could you open a new issue for each issue that you have? Is easy for me to track which issues are resolved or not.

thanks
