### ISSUE TITLE
Including dependencies for new StreamField block types

### ISSUE THREAD

**Issue by FlipperPA** [APSL/puput#81]
I've created three block types for code syntax highlighting, Markdown, and RST types:

https://github.com/FlipperPA/wagtail-components

However, these have Python dependencies: pygments, markdown, and docutils, respectively. How do we feel about adding dependencies to puput to include these block types? I'll start with a generic StreamField I've created, but thought it might be cool to include these as well.

**Comment by marctc** [comment]
Sure. I think there is no problem adding new dependencies.

**Comment by FlipperPA** [comment]
Thanks! I'll close this out. I'm working on adding a StreamField option, and hope to have a PR for discussion soon to see what people think.

**Comment by marctc** [comment]
Thanks!!
