### ISSUE TITLE
Dependencies on rcssmin and rjsmin, a problem on (64-bit) Windows

### ISSUE THREAD

**Issue by bobhy** [APSL/puput#91]
I don't actually expect too much sympathy here, but my install of puput on Windows with 64 bit python just failed trying to build the C extensions for rcssmin and rjsmin, error C++ compiler not found.  
That's true. I don't have a 64-bit compiler installed right now.

Microsoft distributes 'express' and 'community' edition versions for free, but those are 32-bit only.

Sure, I could ratchet down Python to 32 bits, or muck around with MinGW or spend money on VS.  

But if your dependency on the above packages is not too deep and you could allow puput to run (albeit with reduced performance) if they can't be imported, that would be great.

Otherwise, I'll be deferring my experience with puput to another day.  And that's too bad, it looks pretty good...

**Comment by FlipperPA** [comment]
Wagtail had a similar issue with libsass before the 1.0 release for django-compressor, which wasn't really a requirement. Is it worth making these optional instead of required? There are so many different ways to compress CSS and JS, and even then, the performance gains for most blog sites would be negligible performance wise for most implementations of CSS / JS.

Which is a long way of asking: can we just ship Puput with pre-compressed and minified CSS / JS?

**Comment by marctc** [comment]
> I don't actually expect too much sympathy here
Don't worry, we don't discredit anybody whatever it is his OS. We are a community and we have to respect each other.

As @FlipperPA said, this an issue with django-compressor and Wagtail removed time ago.

> Which is a long way of asking: can we just ship Puput with pre-compressed and minified CSS / JS?
Yeah, this is an excelent idea. Let's do this!

**Comment by bobhy** [comment]
I think that is an excellent idea, too.  It will simplify the installation of `puput` for future users.

As for me, I worked around the problem with sympathy from a totally unexpected source, Microsoft, Inc!

It turns out they have been releasing the 64-bit C++ compiler for free to the community for a couple of years now.  It must have been big news in the Python community when it happened, but somehow, I didn't get the memo.

I downloaded MS VC++ 14.0 (which matches Python 3.5 as distributed from python.org) from:

http://landinghub.visualstudio.com/visual-cpp-build-tools

And this allowed me to build `rcssmin` and `rjsmin` and proceed to start working with `puput`.

Thank you, Microsoft!
And thank you here on the project team for engaging on this issue, too.

**Comment by FlipperPA** [comment]
Slight tangent here, but Microsoft has been embracing the Python and Django communities quite a bit lately. They provide support for both `pyodbc` and `django-pyodbc-azure` now: https://blogs.technet.microsoft.com/dataplatforminsider/2016/12/09/sql-server-python-whats-new/

**Comment by marctc** [comment]
Fixed in #134
