### ISSUE TITLE
Produced feed is not valid when entry has header image

### ISSUE THREAD

**Issue by sterago** [APSL/puput#92]
it seems that because of this method https://github.com/APSL/puput/blob/master/puput/feeds.py#L48

the produced RSS feed contains an `enclosure` element, which is invalid because it's lacking the `length` and `type` fields which are required (https://validator.w3.org/feed/docs/rss2.html)

To my understanding the `enclosure` element is only useful for media that has a length, e.g. audio or video, but not for images, therefore my proposed solution would be to remove this method altogether.

I can work on a PR if this sounds reasonable

**Comment by marctc** [comment]
So, where will header image go if we remove `enclosure`?

**Comment by sterago** [comment]
Apparently, the two most common ways of including an image for a feed's item are:
- adding the image within an `enclosure` element
- adding a `CDATA` section with an `img` element inside of the item's `description` field

However, for the first alternative one would need to specify the MIME type, which given the current implementation, results in a "None" value, and a valid `length` which is currently `None`, and in the case of an image should be the size of the file.

The second alternative, instead, allows to just specify the image's source URL without having to worry about the length of the file, whose calculation might require additional processing.

I can implement any of the two. What do you think @marctc ?

**Comment by marctc** [comment]
To be honest, I don't have the enough RSS knowledge to make this decission. So if any of the implementations work choose whatever you think will work better.

thanks!
