### ISSUE TITLE
Description element in produced feed contains entry's body

### ISSUE THREAD

**Issue by sterago** [APSL/puput#93]
Since the description element of RSS feeds is meant to contain a summary of the item, would it make sense to have the `BlogPageFeed.item_description` try to return `item.excerpt` and, only when no excerpt is present, fallback to `item.body` (or a truncated version of it)?

If you agree, I can work on a PR

**Comment by marctc** [comment]
I thought that RSS readers make an excerpt automatically of each blog post. If that's not true, I'm agree on continuing working on this issue.

**Comment by sterago** [comment]
After a deeper look at the RSS specs, it seems that the `description` field of the `item` can either be the full content or just a summary, at discretion of the publisher.
Therefore I would add a boolean `PUPUT_SHORT_FEED_DESCRIPTION` setting and, based on that, have the `item_description` method return the excerpt/truncated body or the full body.

I personally prefer using the excerpt as it's more likely to be devoid of "special" html tags normally present in blog post bodies, which may cause incompatibility issues when parsed by aggregators.

However, from a UX standpoint I find it inconsistent that, when scrolling through feeds from different sources in aggregators, some have the full content and some not, but that's because of the lack of stricter specs in the RSS standard of course.

Shall I proceed with this PR then?

**Comment by marctc** [comment]
Yes, you can proced it. If you want that users can configure if they want the full body or only the excerpt you can add a field to BlogPage model (default to excerpt) instead of adding a new setting.
